package enums;

public enum PaymentStatus {
    PAYMENT_INITIATED,
    PAYMENT_SUCCESS,
    PAYMENT_PROCESSING,
    PAYMENT_FAILED,
    REFUND_INITITATED,
    REFUND_COMPLETED,
    REFUND_PROCESSING,
    REFUND_FAILED
}
